### ISSUE TITLE
Error uploading file

### ISSUE THREAD

**Issue by on4amh** [tamirrosenberg/WiFi-Stepper-Motor-Controller#1]
Hello ,
i copy the file from github into arduino and when loading it into my esp8266, i have the following problem :

ESP8266WiFi : no such file or directory

what am I doing wrong

Francis
ON4AMH
mail : on4amh@gmail.com

**Comment by on4amh** [comment]
Problem solved

**Comment by tamirrosenberg** [comment]
Duplicate issue
