### ISSUE TITLE
error uploading arduino to esp8266

### ISSUE THREAD

**Issue by on4amh** [tamirrosenberg/WiFi-Stepper-Motor-Controller#2]
Hello ,
i copy the file from github into arduino and when loading it into my esp8266, i have the following problem :

ESP8266WiFi : no such file or directory

what am I doing wrong

Francis
ON4AMH
mail : on4amh@gmail.com

**Comment by on4amh** [comment]
Problem solved

**Comment by tamirrosenberg** [comment]
Thanks for the update @on4amh and I'm happy the issue has been solved.
I assume that it may be related to a missing library?

**Comment by on4amh** [comment]
Yes , missing library file

**Comment by tamirrosenberg** [comment]
Thanks, @on4amh, good luck.

**Comment by on4amh** [comment]
One more question
Now i can load the file from arduino IDE to the Esp 8266 the stepper motor turns 1 sec left than 2 sec right , i changed the settings for the steps but the steppermotor turns not how it shud be

**Comment by tamirrosenberg** [comment]
The code should be used using the Blynk App. Each button in the App should operate the stepper motor with different steps. You can see it in the video. I wonder if you were using the App for that and if you tried all the buttons (i.e. Tune, Tune to the sides, and Fine Tune)?

**Comment by on4amh** [comment]
I use Blynk and it works ,but when i tune with blynk the steppemotor turn not smooth , the motor turned not in the same direction , when push on tune fast right or left the motor turn for a time left then a time rihgt , never always right or always left
And it turn and it stop
I tried everything to solve this but i cannot solve this problem

**Comment by on4amh** [comment]
I use the app the Same as yours, the same buttons

**Comment by tamirrosenberg** [comment]
As it sounds, it may be related to the Motor Driver. Which one are you using?

**Comment by on4amh** [comment]
I use the drv8825

**Comment by on4amh** [comment]
![image](https://user-images.githubusercontent.com/22842645/134960461-c262f387-77bb-476e-a343-853a7f34b45e.jpeg)

**Comment by tamirrosenberg** [comment]
Can you please double-check that the Motor lines are connected to the right pins on the Motor Driver?
Also, please re-check that all the Motor lines are connected "well" to the driver, as if some line is a bit loose, it can cause the behavior that you are describing.

**Comment by on4amh** [comment]
Video so you can see

https://user-images.githubusercontent.com/22842645/134962684-b8bbc9d8-2a61-4688-b2de-01ad4b20af01.MOV

**Comment by tamirrosenberg** [comment]
Things that I can think of:
1. Please check the Blynk library version that was uploaded to the IDE. I'm using:
Blynk by Volodymyr Shymanskyy, version 1.0.0-beta.3
2. From the IDE, I'm using the Board "NodeMCU 1.0  ESP-12E" (you can find it from "Tools" --> "Board Manager")
3. Please recheck that the 4 colors lines of the Motor are connected tight to the board. If one of the lines is not connected well, it can cause these "jumps" of the motor.
4. Please recheck that pins RES and SLP on the DRV8255 are connected together, and to the +5V
5. Have you adjusted the Voltage of the DRV8255? Please review: https://forum.arduino.cc/t/update-current-adjustment-for-motor-drivers-drv8825-a4988/400151
6. If you changed the parameters of the steps in the code, please try to revert the change back to the defaults that I published in the code in GitHub.

I will try to think about more options.

**Comment by on4amh** [comment]
thanks for info, i will check everything and keep you posted.
I am going on vacation tomorrow for a few days , so it will be for next week . 73' Francis ON4AMH

**Comment by on4amh** [comment]
Hi , i checked everything today , and now its working fine with you’re first files from 4 month ago .

the problem was bad contact in the motor control cable, i ordered it online at wish poor quality apparently.
when uploading the update of the control from 3 months ago I get the following error message "stray'@' in program " what am I doing wrong

73 francis ON4AMH
